#!/bin/bash

cp .env.${ENV} .env

if [ "${ENV}" == "production" ]; then
    su -c "composer install --no-dev" php_user
else
    su -c "composer install" php_user
fi

php artisan migrate --force
if [ "${RUNNING_ARTISAN_DB_SEEDING}" == "true" ]; then
    echo "Running artisan seed commandline"
    php artisan db:seed --force
fi

echo "Running artisan view:clear commandline"
php artisan view:clear
echo "Running artisan route:clear commandline"
php artisan route:clear
# echo "Running php artisan cache:clear commandline"
# comment out this line to avoid loosing the BEAK urls in REDIS, @luan
# php artisan cache:clear
echo "Running php artisan config:cache commandline"
php artisan config:cache

# php artisan passport:key
set -e
# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
  set -- php-fpm "$@"
fi

exec "$@"